### ISSUE TITLE
Playback on CHIP SoC drops the first .5-1s of sound

### ISSUE THREAD

**Issue by stealthdave** [spatialaudio/python-sounddevice#114]
Using `sounddevice` on a CHIP SoC computer (Raspberry Pi competitor) causes the sound to start playing before the device completes initialization, causing the first .5s-1s of sound to be dropped.  I discovered this while working with the Google Assistant SDK, which uses the `sounddevice` library for playback.  Playing sound using `pyaudio`, while choppy, did not drop any part of the sound.

To recreate, I used `sounddevice` 0.3.9 with `python` 3.4 on the CHIP Linux 4.4 headless OS.  Following the example `play_file.py` from http://python-sounddevice.readthedocs.io/en/0.3.9/examples.html:

> import sounddevice as sd
> import soundfile as sf
> data, fs = sf.read(args.filename, dtype='float32')
> sd.play(data, fs, device=args.device)

Playing file once results in missing audio.  Playing the file a second time in the same Python session (without closing the device) plays all audio with no drops.

This example of `pyaudio` played all sound, but was choppy.
https://stackoverflow.com/questions/17657103/how-to-play-wav-file-in-python

[Chip forum thread for reference](https://bbs.nextthing.co/t/strange-audio-output-behavior-missing-first-few-words/5495/16)

**Comment by mgeier** [comment]
This sounds like an issue with the underlying PortAudio library, but PyAudio uses it, too ....

Are you using the same version of PortAudio in both cases?

You can check with [sounddevice.get_portaudio_version()](http://python-sounddevice.readthedocs.io/en/latest/#sounddevice.get_portaudio_version) resp. [pyaudio.get_portaudio_version()](https://people.csail.mit.edu/hubert/pyaudio/docs/#pyaudio.get_portaudio_version)/[pyaudio.get_portaudio_version_text()](https://people.csail.mit.edu/hubert/pyaudio/docs/#pyaudio.get_portaudio_version_text).

You could also try to temporarily disable the hiding of PortAudio output by removing the call to [_ignore_stderr()](https://github.com/spatialaudio/python-sounddevice/blob/88e5ea58b0193f46aed8fa7ce1ac336b40195469/src/sounddevice.py#L2677).

The choppiness might be caused by inappropriate latency/block size settings.

**Comment by stealthdave** [comment]
They're both using the same version `PortAudio V19-devel (built Feb 16 2014 00:44:59)`.  I tested using the same virtual environment.

Unfortunately, calling `_ignore_stderr()` just prior to `play` made no difference; the same delay was experienced.

**Comment by mgeier** [comment]
I was talking about *disabling* the call to `_ignore_stderr()`, which happens close to the end of `sounddevice.py`.
This is supposed to show PortAudio messages, which are normally hidden.
Are there any errors printed to the terminal when you remove `_ignore_stderr()`?

It's good to know that both use the same PortAudio version, but that means I cannot simply blame it on PortAudio ...
However, you are not using the latest PortAudio version, the latest one should be something like `v190600_20161030`. You should try it!

You should also check which device number you are using in your different scenarios. Is it the same one?
You should check for all available devices with `sounddevice.query_devices()`.

**Comment by stealthdave** [comment]
I'm now able to reproduce this issue using `aplay` and a different sound file, so I'm fairly certain now that this is _not_ a `sounddevice` bug.  Thank you for your help, and sorry for the inconvenience!

**Comment by mgeier** [comment]
No problem. Good luck finding the solution!
