### ISSUE TITLE
Build should depend on PortAudio

### ISSUE THREAD

**Issue by yurivict** [spatialaudio/python-sounddevice#119]
Currently, during build, it uses the hardcoded PortAudio interface in ```sounddevice_build.py```.

It shouldn't use hardcoding. It should read the interface from the actual PortAudio library.

(What if PortAudio changes?)

**Comment by mgeier** [comment]
AFAIK, this is just the way how CFFI is used.

The problem with using CFFI with arbitrary `.h` files (like `portaudio.h`) is that the C parser that's used only supports a subset of preprocessor directives (like `#define` and `#include`).

Feel free to try it with `portaudio.h`, it will simply not work.

But even if it would work, the approach is still problematic, because there is no reliable way to find `portaudio.h` on the target system. It's most likely not even there.

So we would have to provide our own copy of `portaudio.h`, which would be just another form of hardcoding.

Or am I missing something?

> What if PortAudio changes?

Ideally, everything just continues to work.
Any changes in PortAudio will most likely be backwards compatible. No problem.
If they are adding new functions, they will not be available until we add them to `sounddevice_build.py`. But we would need some Python wrapping anyway, the Python API is not auto-generated from the C API. So whenever something is added, the `sounddevice` module will have to be changed anyway.
But don't worry, this will happen very rarely. PortAudio currently has a very slow pace of development.

**Comment by yurivict** [comment]
Thank you for your explanation!
