### ISSUE TITLE
Error Getting Mac OS X Sound Output

### ISSUE THREAD

**Issue by UsersDoProgram** [spatialaudio/python-sounddevice#128]
I made the following program in an attempt to try and retrieve all the audio that is being played on my Mac and replay it but everytime I run the code in [main.txt](https://github.com/spatialaudio/python-sounddevice/files/1858300/main.txt), I run across the following output,

Default Devices:
```
> 0 Built-in Microphone, Core Audio (2 in, 0 out)
< 1 Built-in Output, Core Audio (0 in, 2 out)
```

```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    with sd.Stream(channels=2,dtype="float32",callback=callback):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sounddevice.py", line 1654, in __init__
    **_remove_self(locals()))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sounddevice.py", line 772, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Invalid number of channels [PaErrorCode -9998]
```

**Comment by tgarc** [comment]
Hi there! Could you please paste the text of the program or post it in some way that doesn't require downloading? I think this error occurs most commonly when trying to record with a device that is playback only or vice-versa. Without looking at your code, I would suggest specifying ``device=(0,1)`` when instantiating Stream.

**Comment by mgeier** [comment]
@UsersDoProgram You are switching input and output device in your code:

```python
dev = sd.default.device
dev[0],dev[1] = 1,0
sd.default.device = dev
```

The first listed device is the *input* device, the second is the *output*, same order as when you are saying "I/O". You are trying to use the output device for input and vice versa.

If you simply remove everything regarding "device", it should work, because the defaults are already correct.

Or, as @tgarc suggested, you can use `device=(0,1)` in the `sd.Stream()` constructor.

Or, if you want to use `sd.default`, you can try this:

```python
sd.default.device = 0, 1
```

... but this doesn't change anything in your case, since that's already the default.

Maybe the "arrows" in the device list are confusing:

    > 0 Built-in Microphone, Core Audio (2 in, 0 out)
    < 1 Built-in Output, Core Audio (0 in, 2 out)

The default input points to the "inside", i.e. towards the device name, while the default output points to the "outside", away from the device name.
I couldn't come up with anything less confusing ...

**Comment by mgeier** [comment]
@UsersDoProgram Did you manage to solve your problem?

**Comment by UsersDoProgram** [comment]
@mgeier Sadly, I haven't but I C++'s libportaudio has brought me closer to finding a solution.

**Comment by khlorghaal** [comment]
This error message is misleading. There should be a separate error for mismatched input<->output.

**Comment by mgeier** [comment]
@khlorghaal  Do you mean the message `Invalid number of channels`?

This message comes directly from the PortAudio library, so we cannot change it.

But we could probably do some additional checks *before* trying to create the stream.
E.g. we could try to call `check_input_settings()` and `check_output_settings()`.
This way, the error message might contain information whether it's about "input" or "output" channels.
Do you think this would help?

**Comment by mgeier** [comment]
@khlorghaal I've created #242 to address your suggestion, but I'm not sure if it's a good idea. Please express your opinions over there.
