### ISSUE TITLE
Jack on Ubuntu

### ISSUE THREAD

**Issue by juandagilc** [spatialaudio/python-sounddevice#13]
Hello,
I am using sounddevice in a virtual machine running Ubuntu 14.04 LTS. When I import sounddevice I get the next three messages (the application works anyway!):
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```

I realized that if start jack before I run my python program these messages disappear. But then I obviously need to stop jack afterwards.

Do you know if there is way to do this from within my python script? I tried something similar to what you suggested me here https://github.com/spatialaudio/python-sounddevice/issues/10#issuecomment-158344854 but instead I get this error when the program finishes:
```
python: src/hostapi/jack/pa_jack.c:820: Terminate: Assertion `err == 0' failed.
Aborted (core dumped)
```
Is this https://jackclient-python.readthedocs.org/en/0.4.0/ for that purpose?

Again, I am just a n00b so I would appreciate your help!

**Comment by mgeier** [comment]
The three messages are "normal", because PortAudio checks if JACK is available. If it's not, this causes the messages and PortAudio just continues without JACK support.

If JACK is already running, PortAudio's check for JACK is successful (not causing any messages), and it continues with JACK support.

Either way, the messages don't mean there is something wrong, as you said, it works anyway (just without JACK support).

To get rid of those annoying messages, I made PR #12. If you want, you can try the `redirect-stdout` branch, which shouldn't show the messages in any case.
You don't need the work-around from #10 for this.

> Do you know if there is way to do this from within my python script?

Do you actually want to use JACK or not?

I don't know what's the best way to start the JACK daemon (`jackd`) from Python.
You can try to use https://github.com/spatialaudio/jackclient-python or you can try to start `jackd` with the `subprocess` module: https://docs.python.org/3/library/subprocess.html.

Either way, you shouldn't start/stop JACK while the `sounddevice` module is loaded, because this causes the crash you were mentioning.

> Is this https://jackclient-python.readthedocs.org/en/0.4.0/ for that purpose?

What do you mean by that?
That's just the link to the docs ...

**Comment by juandagilc** [comment]
I linked the docs but what I meant was if ```jackclient-python``` had the ability to start and stop JACK from python. I tried using the ```subprocess``` module but now I understand I cannot stop JACK while ```sounddevice``` is loaded. I can go around with the solution in https://github.com/spatialaudio/python-sounddevice/issues/10 when I need to use JACK.

Thanks a lot!

**Comment by mgeier** [comment]
I just want to add a little piece of information: The "official rule" is that you shouldn't start/stop JACK while `sounddevice` is loaded. However, there is a work-around: You can use the "hidden" function `sd._terminate()`, which will terminate PortAudio, then you can start/stop JACK, and afterwards, you can call `sd._initialize()` to re-initialize PortAudio. This should (hopefully!) not lead to a crash, but you should be aware that the list of devices (and therefore their device IDs) will change.

These "hidden" functions might at some point become "official" (see #3), but until now there wasn't any demand for that.
