### ISSUE TITLE
Channel mapping with callback

### ISSUE THREAD

**Issue by johnroper100** [spatialaudio/python-sounddevice#151]
Is there a way to do channel mapping while using an audio callback instead of a blocking stream?

**Comment by mgeier** [comment]
There are two different kinds of "channel mapping".

* The platform-dependent kind in `AsioSettings` and `CoreAudioSettings`. Those should always apply, independent of blocking or non-blocking. I don't really have experience with that, please tell me if it doesn't work for you.

* The platform-independent `mapping` argument in `play()`, `rec()` and `playrec()`. This is only available in those 3 functions. This is not very fancy because it simply creates as many channels as the highest channel number and fills the unneeded channels with zeros. This is implemented in Python, which means that you can just implement the same thing in your own code, be it with blocking or non-blocking streams.

**Comment by johnroper100** [comment]
Well, my audio callback, it just runs `output[:] = data`

**Comment by johnroper100** [comment]
Can I call output multiple times out send different things to each channel.

**Comment by johnroper100** [comment]
It seems like I can

**Comment by mgeier** [comment]
Yes, `output` is just a NumPy array. You can assign to its content as many times as you want. You can assign all the content once or in parts one after each other. You should just make sure that you have assigned to each element at least once before you reach the end of the callback. If you don't have data for some channels, you should fill them with zeros. If most of your channels are silent, you can do `output.fill(0)` and afterwards assign only the channels for which you have data.

**Comment by huangzhenyu** [comment]
> Assuming you use NumPy (i.e. not the "raw" stream), you can try something like this:
> 
> ```python
> output[:, out_mapping] = data[:, in_mapping]
> ```
> 
> For example, if you want to record channel 3 and 7, use `in_mapping = [2, 6]`.
> If you want to play back on channels 1 and 4, use `out_mapping = [0, 3]`.

index 6 is out of bounds for axis 1 with size 2... how to do with this?

**Comment by HaHeho** [comment]
> index 6 is out of bounds for axis 1 with size 2... how to do with this?

See my response in https://github.com/spatialaudio/python-sounddevice/issues/362#issuecomment-893304431.
