### ISSUE TITLE
Analyzing the input frequency

### ISSUE THREAD

**Issue by charlsagente** [spatialaudio/python-sounddevice#156]
Hello guys, I am using an audio interface where I plug my guitar and I was able to run your `Plot Microphone Signal(s) in Real-Time` example successfully where I can see the audio signal. 

I would like to analyze the frequency of the signal, in this case I would like to know which notes I am playing. I don't have experience with Numpy but I think I have to analyze the array data in the callback functions. 

Can you share with me how can I get that information?

**Comment by mgeier** [comment]
The job of the `sounddevice` module is just to get data to and from the sound card. For generating and/or analyzing and/or further processing the data you will likely need another library.

There are many functions for signal analysis in NumPy and SciPy, but there are also several more specialized libraries for sound analysis.

I cannot really give you concrete advice, but you should probably just search the web for "pitch estimation", of course always in combination with "Python", if you want to use that.
You might also find something if you look for "guitar tuner", because those often also can detect the note you are playing.

Other than that, I can just give you some pages with some further, but quite unsorted links:

* http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/signal-processing/index.ipynb
* http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/signal-processing/fft.ipynb
