### ISSUE TITLE
Failed to install with `pip install sounddevice --user`

### ISSUE THREAD

**Issue by DaHoopster** [spatialaudio/python-sounddevice#16]
Not sure what happened but I see the following output after `$pip install sounddevice --user`. Can't move forward at all, please help.

Mac OSX 10.10.5 (Yosemite)
python 2.7.7

```
Downloading/unpacking sounddevice
  Downloading sounddevice-0.3.1.tar.gz
  Running setup.py egg_info for package sounddevice
    
    error: package directory '_sounddevice_data' does not exist
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/sounddevice.egg-info

writing requirements to pip-egg-info/sounddevice.egg-info/requires.txt

writing pip-egg-info/sounddevice.egg-info/PKG-INFO

writing top-level names to pip-egg-info/sounddevice.egg-info/top_level.txt

writing dependency_links to pip-egg-info/sounddevice.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/sounddevice.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



error: package directory '_sounddevice_data' does not exist

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/t6/c_sf37fx0yj_6glzll5ttp_r0000gn/T/pip-build/sounddevice
Storing complete log in /Users/dahoopster/Library/Logs/pip.log
```

**Comment by mgeier** [comment]
Hmm, it seems that `pip` chooses the `.tar.gz` file instead of the more appropriate [wheel file](https://pypi.python.org/packages/py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36/s/sounddevice/sounddevice-0.3.1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36-none-macosx_10_6_x86_64.whl).

I don't know why this happens and I'm not sure how to fix this ...

As a first attempt, can you please try to re-install/update the newest versions of `pip` and `setuptools`?

**Comment by mgeier** [comment]
Can you please provide the output of `platform.machine()` on your computer?

**Comment by DaHoopster** [comment]
The output of my `platform.machine()` is:

```
x86_64
```

**Comment by mgeier** [comment]
OK, that doesn't seem to be the problem, did you try to upgrade `pip` and `setuptools`?

**Comment by DaHoopster** [comment]
Yes, it worked after I installed python 2.7.11 with homebrew. Thanks !
