### ISSUE TITLE
ValueError: Number of samples not divisible by channels

### ISSUE THREAD

**Issue by bballjbv1** [spatialaudio/python-sounddevice#167]
```python
with sd.Stream(samplerate=RATE, blocksize=CHUNK, dtype='int32', latency='low', callback=None) as s:
    wave = signal.square
    t =.002
    sps = 44100
    atten = .015
    while True:
        freq=440
        waveform= wave(2*np.pi*(np.arange(t*sps))*freq/sps)
        waveform_quiet=waveform*atten
        wave_int = waveform_quiet * 2147483647
        s.write(np.ascontiguousarray(wave_int, np.int32))
```

So along the way I realized that I wanted to make a single period based sound sample and propagate that within a loop without using the limited play() stream.  I understand that you cannot hear a sound wave the same at (1/440) of a second for a concert A (440hz) note. But if you loop a single period of a sound many times you will still hear the sound because its concatenated. You can also put some of the waveforms parameters within the loop to change the amplitude and frequency almost in real time, that is the main goal im trying to accomplish. Unfortunately, stream write() wont allow me to have a small time period like the sd.play() can. Is there anyway to alleviate this problem, or is it just a problem with sounddevices limitations?

**Comment by mgeier** [comment]
I took the liberty of fixing your example code, I hope I didn't mess it up.

In order to make your code actually work, I had to add a few things, and I switched to using the default data type `'float32'` to avoid some calculations:

```python

import numpy as np
from scipy import signal
import sounddevice as sd

sps = 44100
freq = 440

wave = signal.square
t = .002
atten = .015

waveform = wave(2 * np.pi * (np.arange(t * sps)) * freq / sps)
waveform_quiet = waveform * atten
waveform_32bit = waveform_quiet.astype('float32')

with sd.Stream(samplerate=sps, latency='low') as s:
    while True:
        s.write(waveform_32bit)
```

Running this, produces the error you were mentioning in the title:

    ValueError: Number of samples not divisible by channels

How many channels do you want?

I guess you want one?

If yes, you should use `channels=1`:

```python
with sd.Stream(samplerate=sps, channels=1, latency='low') as s:
    while True:
        s.write(waveform_32bit)
```

Now this produces some sound :slightly_smiling_face: but it's not quite 440 Hz :frowning_face:

Did you actually mean to use `t = 1 / freq`?

> without using the limited play() stream

I agree that the `sd.play()` function is limited, but it can be used to get the same result as above:

```python
import numpy as np
from scipy import signal
import sounddevice as sd

sps = 44100
freq = 440

wave = signal.square
#t = .002
t = 1 / freq
atten = .015

waveform = wave(2 * np.pi * (np.arange(t * sps)) * freq / sps)
waveform_quiet = waveform * atten
sd.play(waveform_quiet, samplerate=sps, latency='low', loop=True)
sd.wait()
```
