### ISSUE TITLE
OSX Stereo recording is actually duplicate mono streams

### ISSUE THREAD

**Issue by Jello** [spatialaudio/python-sounddevice#172]
I'm doing a duplex stream to record and playback audio using SoundDevice. I'm getting a stereo recording, but both streams are identical rather than properly recording in stereo on a Mac. The same code works correctly on Windows and produces non-identical audio streams.

Below is essentially what my code is. Works correctly on Windows, and Audacity on the Mac can properly record in stereo. Any ideas?

````
numChannels = 2

soundfile = sf.SoundFile(WAVE_OUTPUT_FILENAME,mode='x',samplerate=sd.default.samplerate,channels=numChannels,subtype="FLOAT",)

def rec_callback(indata, outdata, frames, time, status):
    if len(indata > 0):
        soundfile.write(indata)
with sd.Stream(channels=numChannels,dtype=dataType,blocksize=sd.default.blocksize,callback=rec_callback):
    listener.join()
````

**Comment by mgeier** [comment]
Please provide the device name that's selected in Audacity as well as the output of `sd.query_devices()`.

**Comment by Jello** [comment]
The results of query_devices()
>>> import sounddevice
>>> sounddevice.query_devices()
> 0 Built-in Microphone, Core Audio (4 in, 0 out)
< 1 Built-in Output, Core Audio (0 in, 2 out)

Usually I've seen the first line return 2 in instead of 4 in though. I think ssh'ing into my Mac caused 2 additional channels to be created, but it's usually only 2.

For Audacity I see Core Audio -> Built-in Microphone -> 2 (Stereo) Recording Channels -> Built-in Output

It also now shows options for 3 and 4 as well, but normally only shows 2.

**Comment by mgeier** [comment]
Sorry, I don't know why you get two copies of a mono signal instead of a proper stereo signal.

Normally I would say that's the fault of PortAudio, but Audacity also uses PortAudio. But they use a slightly patched version, so there might still be a difference.

And an `ssh` connection causing the spontaneous creation of 2 sound device channels sounds a bit mysterious, is this expected behavior?
Do all 4 channels have the identical signal? Or is it two left and two right?

Just to be sure, can you please try making recordings with `sounddevice.rec()` and `sounddevice.playrec()` to check if the same problem happens there?

**Comment by Jello** [comment]
I'm not sure what happened with the sound channels. It went from 2 to 4 and now it's persisting after reboot. I'm only concerned about stereo though.

sounddevice.rec() does have different data for both channels recorded.

I'm not sure where the error is with the sd.Stream, my above code in the first post is basically the entirety of what I'm doing. Is the write being done correctly?

**Comment by Jello** [comment]
So I think I fixed the issue. Earlier in the program, there's a call to sf.blocks with always_2d=True passed in. This seems to have effected sf.Soundfile, so that when soundfile.write is called, it forces both streams to be duplicates. I'm not sure why always_2d effects the writes or why this appears to have global effects. I'm also not sure why this had this effect on the Mac and not Windows.
Anyhow, seems to be a bug in SoundFile and not in SoundDevice.

**Comment by mgeier** [comment]
It would be great if you could provide runnable code that shows the problem, so that others can try to reproduce it.

> Is the write being done correctly?

It looks OK, but I can't say for sure because the code is incomplete.

I would not write to the file directly in the callback function but rather use a queue, as in the example [rec_unlimited.py](../blob/master/examples/rec_unlimited.py).

**Comment by Jello** [comment]
Yeah I switched to using a queue.

The issue here was in soundfile's writing of a wav file, not in sounddevice.

```
startQueue = queue.Queue()
endQueue = queue.Queue()

for block in sf.blocks("file.wav",dtype='float32',blocksize=8192,overlap=0, always_2d=True):
    startQueue.put(block)
    endQueue.put(block)


numChannels = 2

soundfile = sf.SoundFile("output.wav",mode='x',samplerate=sd.default.samplerate,channels=numChannels,subtype="FLOAT",)

def rec_callback(indata, outdata, frames, time, status):
    if len(indata > 0):
        soundfile.write(indata)
with sd.Stream(channels=numChannels,dtype=dataType,blocksize=sd.default.blocksize,callback=rec_callback):
    listener.join()

```

The earlier call to sf.blocks with always_2d=True set causes the later writes with SoundFile to also be forced into a 2d duplicate mono output on OSX. Removing always_2d=True fixed the issue.

**Comment by mgeier** [comment]
OK, I see. I don't have a Mac, so I can't check this for myself.

Since this issue seems to be independent from the `sounddevice` module, it would be great if you could come up with a fully runnable code example (including all the necessary `import` statements) that doesn't involve the `sounddevice` module and post it to https://github.com/bastibe/SoundFile/issues/235.
