### ISSUE TITLE
Mapping problem on channel 1

### ISSUE THREAD

**Issue by maximillion90** [spatialaudio/python-sounddevice#18]
So I am trying to output an impulse on a particular channel of a large sound card (not the same channel each time) I found Sounddevice very useful however I get some strange issues when mapping my sample to channel one only which doesn't happen with any other mapping. The following command:

`sd.play(impulse.samples, samplerate=96000, mapping=[1])`

appears to output on both channels one an two when I expect audio on just channel 1 while 

`sd.play(impulse.samples, samplerate=96000, mapping=[2])`

outputs on channel 2 as expected and all other channels I have tested appear to work as channel 2 does. Even

`sd.play(impulse.samples, samplerate=96000, mapping=[1, 3])`

outputs on channels 1 and 3 as I expect. I am not ruling out that i am missing something but I would appreciate some help very much.
Just incase you need it i have checked the impulse samples, dtypes and they all appear to be correct

Thanks.

**Comment by maximillion90** [comment]
Little bit more information on this, tried this on my Ubuntu machine as well and rather than only getting the issue when sending just to channel 1 as described above. The last channel always appears to cover two channels example:
`sd.play(impulse, samplerate=48000, mapping=[1,3,5], device = 5)`
and I will get audio on 1 3 5 and 6

**Comment by mgeier** [comment]
I think I have an explanation for what you described first (about duplicating the first channel).

This is actually a feature of PortAudio, but it is not available on all host APIs. Probably it's also just a feature of the underlying audio backend(s). AFAIK, this will happen e.g. on ALSA, but not on JACK.

When you use `mapping=[1]` (and mono audio data), this will lead to `channels=1` internally. Now on some (most?) host APIs (ALSA among others), PortAudio will duplicate this one channel to both output channels. This is actually quite useful for many simple cases, but obviously not at all helpful for your use case.

I don't really know if there is anything I can do to change this behavior.

I can try to force `channels=2` instead of `channels=1`, but I think this might cause problems in other use cases.

But now to your other comment: I have no idea why the last channel should be duplicated. This doesn't happen with JACK, but I couldn't yet test this with ALSA on a multi-channel soundcard.

**Comment by maximillion90** [comment]
Ok well thanks for the response. I can force channels to 2 myself and try that save you doing it. As for the Jack comment I might look into moving to jack instead of alsa if this solves my problem but I want to test it before I move. Worst comes to it when I want channel one I will will send channel two and silence it myself. thanks for the pointers and confirming its not my donkey hoofs.

**Comment by mgeier** [comment]
You can't use `channels=2` when using `mapping=[1]` because former will be ignored. But it should work if you add a second channel with silence.

However you should **not** get any audio on channel 6 if you use `mapping=[1,3,5]`. Are you still having this problem?

**Comment by maximillion90** [comment]
Yeah I never found a work around in the end I retreated back to my pyaudio code and carried on fighting with that.

**Comment by mgeier** [comment]
And PyAudio doesn't have the same problem?
It should, because it also just uses PortAudio.

My goal with the `sounddevice` module is to be able to do everything that can be done with PyAudio (just with a better API) and more.

It would be *very helpful* if you could tell me what you are able to do with PyAudio that you are not able to do with `sounddevice`.

**Comment by maximillion90** [comment]
Sorry let me clarify my statement. There is nothing I can do with pyaudio that I can't do with sounddevice and the API for sounddevice is definitely better of that there is no doubt.
The reason I went back to pyaudio is that I already had most of the functions I needed coded with that and since I appear to have to silence channels in sounddevice and create the mapping in pyaudio rather than re-writting all the stuff i already had to use sound device I stuck with my already done pyaudio code.  Purely that i didn't discover sounddevice first.

**Comment by mgeier** [comment]
OK, thanks for the clarification.

If you happen to find a way to properly avoid the channel duplication, please tell me!

I'll leave this issue open, probably someone else out there has an idea for a solution?

**Comment by mgeier** [comment]
OK, I think I found a solution that doesn't have too many bad side effects in other situations: #20.

@maximillion90: Can you please check if this works for you?

**Comment by maximillion90** [comment]
Yeah that appears to work as expected now. It allows you to map single channels with no duplication. If i send it too 1 i get just one if i send it to 1 and 3 i get just 1 and 3. Good Work.

**Comment by mgeier** [comment]
Thanks for testing this!
