### ISSUE TITLE
Proper threading and thread-safety with sounddevice?

### ISSUE THREAD

**Issue by sparkyb** [spatialaudio/python-sounddevice#187]
I'm building a higher-level multi-channel audio playback library built on top of sounddevice that wraps sounddevice and some other libraries (like PySoundFile and python-samplerate) to support easily reading audio files, playing multiple files as once (may require automatic samplerate conversion), adjusting/fading volume, complex channel remapping, and playback event callbacks. I'm a bit confused trying to figure out what is best practice for how many threads to use and what to do on each thread and yet be threadsafe enough to hide this complexity from users of my library who just want to asynchronously play audio files, adjust their volume while they're playing, and be alerted when they've finished without having to actually think about the streaming and so forth.

From examples it seems standard practice to use callback streams rather than blocking streams and to use a queue to pass blocks of samples from the thread that is generating the data to the callback function (running in a thread created by PortAudio, I assume) in order to prevent the callback from being able to block. Doing this, I effectively have 3 threads: the main thread that application would use to request sound files to play, a processing thread in my library that does the work of reading those sound files in chunks and enqueuing them (asynchronously with respect to the main thread), and the stream callback thread.

One question I have is, what's the value of having that separate processing thread instead of doing all the file reading, channel remapping, etc in the callback or just writing to a blocking stream from the processing thread? I know that the callback should do as little as possible so it doesn't block, but if my processing thread can't generate the blocks of audio at the same rate the callback thread consumes them, then I'm going to get audio glitches/drop-outs anyway. Is this extra thread not just overhead if I need to hope I can generate audio fast enough regardless? Is the callback blocking for too long somehow worse than it just returning zeros one frame if the queue is empty? Or is there some reason it needs to return faster than the full amount of time between frames? Or is it simply about using the size of the queue as a buffer so that you won't get dropouts if an occasionally slow to generate frame only slightly drains the queues as long as the average is fast enough?

**Comment by mgeier** [comment]
Sorry for the late response!

First of all, you should consider whether Python is really the right language for your use case.

If you want a reliable library that makes efficient use of multiple CPUs, you might be more successful with a compiled language, such as e.g. Rust or C++ or even in C.

Very recently, I've done a few experiments in Rust that sound kinda similar to what you are trying to do, see https://github.com/mgeier/disk-streaming.

Having said this, as long as you don't need a very short latency, you might be fine doing this with Python (even if the resulting library may be more CPU-hungry than other solutions).

> From examples it seems standard practice to use callback streams rather than blocking streams ...

To some extent this may be a matter of taste. I personally prefer using callback streams.

> ... and to use a queue to pass blocks of samples from the thread that is generating the data to the callback function

Yes, that's pretty common.

> ... (running in a thread created by PortAudio, I assume)

Exactly.

> what's the value of having that separate processing thread instead of doing all the file reading, channel remapping, etc in the callback

Reading data from a file (or opening a file, or writing, ...) might some times take longer than normal, and if you do everything in the audio callback, you might have dropouts because of that.

Of course on average reading from file must be faster than real-time, but by using a queue (as long as it is reasonably filled), you can compensate some delays that happen from time to time.

If you use very long block sizes, you might not need this kind of buffering, but you never know how long your disk (or even network drive!) might block.

> ... if my processing thread can't generate the blocks of audio at the same rate the callback thread consumes them, then I'm going to get audio glitches/drop-outs anyway.

That's true. On average.
But with a bit of buffering you can avoid occasional glitches, as long as it doesn't happen too often (and there is enough time to re-fill the queue).

> Is the callback blocking for too long somehow worse than it just returning zeros one frame if the queue is empty?

No, that's basically the same thing (and it's bad). But the queue should not be empty! If the queue is empty, you have chosen a too short length.

> Or is it simply about using the size of the queue as a buffer so that you won't get dropouts if an occasionally slow to generate frame only slightly drains the queues as long as the average is fast enough?

I should probably have read your whole text before answering.
Because that's exactly it. That's basically what I've tried to say above ...

**Comment by sparkyb** [comment]
I appreciate the response. I went ahead with my work anyway, and so far things seem fine. I considered deleting my question since I have things working, but I wanted to see if there was anything I was missing.

**Comment by mgeier** [comment]
If you work is open source, please consider posting a link here. I would be interested and probably others, too!

**Comment by sparkyb** [comment]
I would love to do that. I'm currently in the process of trying to convince my boss (and through him our investors) to let me open source this (and other python libraries I've been writing for this project).
