### ISSUE TITLE
Sounddevice.InputStream: Does not record audio with given input parameters

### ISSUE THREAD

**Issue by DennisMAtGit** [spatialaudio/python-sounddevice#200]
Hello,

I will try to explain my problem as clearly as possible. I developed an audio manager, whose one of the functions is audio recording. The language I used is `Python 3.6.2` on `Windows 10`. The application utilizes the `Sounddevice` library for the recording function. The issue is the library records the audio with the settings specified under windows sounds settings `Recording / Mic Properties / Advanced` rather than using the parameters given as input to the record function. For example, lets say it is selected in the windows sounds settings as `2 Channel, 16 Bit, 44000 Hz (CD-Quality)` and the record function call looks like below:

    sounddevice.InputStream(samplerate=48000, channels=2, callback=self.callback)

Now, the `Sounddevice` is supposed to record audio at 48 kHz but it records the audio at 44000 Hz and upsamples it to 48 KHz. Why is it so? Why the `Sounddevice` is not overwritting or updating the windows sound settings? What can I do to solve this problem?

A minimal working example:

    import sys
    import queue
    import tempfile
    import numpy as np
    import sounddevice as sd
    import soundfile as sf
    assert np

    q = queue.Queue()

    def callback(indata, frames, time, status):
        """
        This is called from a separate thread for each audio block
        """
        if status:
            print(status, file=sys.stderr)
        q.put(indata.copy())

    # Unique file name for every recording
    filename = tempfile.mktemp(prefix='untitled_', suffix='.wav', dir='')
    # Make sure the file is open before recording anything
    with sf.SoundFile(filename, mode='x', samplerate=48000, channels=2) as file:
        with sd.InputStream(samplerate=48000, channels=2, callback=callback):
            print('#' * 80)
            print('press Ctrl+C to stop the recording')
            print('#' * 80)
            while True:
                file.write(q.get())

But make sure that the windows sound settings has a different sampling rate than in the function call.

Thank you and looking forward to your feedbacks.

**Comment by mgeier** [comment]
> I developed an audio manager

Cool! Is this open source software? Can you provide a link?

> it records the audio at 44000 Hz and upsamples it to 48 KHz

Just out of curiosity: how do you even know this happens?

> Why is it so? Why the `Sounddevice` is not overwritting or updating the windows sound settings?

Well, the `sounddevice` module doesn't do much on its own. It delegates most of the work to the underlying PortAudio library, see http://portaudio.com/.

So the short answer is: I don't know, because the `sounddevice` module doesn't really do any of this.

There are only two things (that I know of) that you can try from the Python side:

* Try different host APIs. In your device list you might have entries for the same physical device, but with different host APIs: "MME", "Windows DirectSound", "Windows WASAPI", "Windows WDM-KS", "ASIO". You should try all of them, maybe one behaves as you would expect.

* For the special case of "WASAPI", you can try using "exclusive" mode, see https://python-sounddevice.readthedocs.io/en/0.3.13/api.html#sounddevice.WasapiSettings

If none of this works, you should ask your questions at the PortAudio mailing list: http://portaudio.com/contacts.html

**Comment by mgeier** [comment]
@DennisMAtGit Any news?

**Comment by DennisMAtGit** [comment]
Sorry, I did not get any time to work on this further. Hence, it can be closed.
