### ISSUE TITLE
How to select Channels on Stream ?

### ISSUE THREAD

**Issue by dschiller** [spatialaudio/python-sounddevice#219]
Non Streaming:

```
recording = sd.rec(int(self.duration * self.fs), dtype='float32', mapping=[4, 5])
```

Streaming:

```
with sd.InputStream(int(self.duration * self.fs), blocksize=1024, dtype='float32', callback=audio_callback):
                sd.sleep(int(self.duration * 100))
```

How to set ``mapping=[4, 5]`` here ?

**Comment by dschiller** [comment]
Found it:

```
asio_out = sd.AsioSettings(channel_selectors=[4, 5])
with sd.InputStream(int(self.duration * self.fs), blocksize=1024, dtype='float32', callback=audio_callback, extra_settings=asio_out):
                sd.sleep(int(self.duration * 100))
```

**Comment by mgeier** [comment]
It's great that you found a solution!

Nevertheless, I would like to clarify a few things:

The "Non Streaming"/"Streaming" dichotomy is not quite right, I would rather call it "High Level"/"Low Level".

The "high level" convenience function `rec()` is actually implemented using the "low level" class `InputStream`.

The `mapping` argument is implemented in the custom callback function of `rec()`:

https://github.com/spatialaudio/python-sounddevice/blob/a176bbc9d5dd777a380214dcc77909aae4e7d33d/sounddevice.py#L2459-L2467

This cannot be implemented in the `InputStream` class itself, because its callback function is reserved to be implemented by the user. If you implement your own callback function, you can implement something similar to the `mapping` argument if you want.

On the other hand, `AsioSettings` uses a platform-specific feature of PortAudio to select a subset of channels at a much lower level, in a way that `InputStream` thinks that those are actually all channels of this device. In your callback function, you can still choose to not use all those channels.

Please note that selecting channels with `AsioSettings` is typically more efficient than selecting channels "manually" in the callback function. But latter is platform-independent, that's why I implemented it anyway in `rec()`.

For completeness' sake, this is how the `mapping` argument is implemented for output channels (used in `play()` and `playrec()`):

https://github.com/spatialaudio/python-sounddevice/blob/a176bbc9d5dd777a380214dcc77909aae4e7d33d/sounddevice.py#L2470-L2480

Please note that care has been taken to write zeros wherever no audio data is available.

**Comment by dschiller** [comment]
@mgeier Thanks a lot!

**Comment by mgeier** [comment]
I guess this issue can be closed. @dschiller If you have further questions, don't hesitate to ask!
