### ISSUE TITLE
Sounddevice in Spyder

### ISSUE THREAD

**Issue by ninadfr** [spatialaudio/python-sounddevice#222]
Hello !
I am currently working on a project at school. For this I have to plot an oscilloscope. I found on the sounddevice page a programm called "plot_input" which is working, BUT only if I execute it in my computer terminal. The problem is that I need to plot it in a Tkinter interface in order to create a small application. What can be the reasons why it is only working on my computer terminal and not on an IPython console ? Any kind of help and answer would really be appreciated ! Thank you !

Nina

PS : sorry for my english !

**Comment by mgeier** [comment]
You are name-dropping quite a few tools: Tkinter, Spyder, IPython console (you mean Spyder's built-in console?). By mentioning the `plot_input.py` example, you are implicitly talking about Matplotlib and its `FuncAnimation` as well.

That's quite a lot.

If you want to create a "small application" with Tkinter, why would you need Spyder or IPython?

If you want to run something in Spyder, why would you need Tkinter?

What do you really want to do?

Do you want to display a Matplotlib plot in a Tkinter GUI?
That's certainly possible, you should find help in the interwebs, but this is out-of-scope here.
Once you have a minimal working example, you can try to add `sounddevice` functionality.
If you have problems with that, feel free to ask again here!

> What can be the reasons why it is only working on my computer terminal and not on an IPython console ?

The reasons for that might be quite complicated, it probably has to do with different event loops running at the same time. But I'm not sure whether that's relevant ...

If you need help with that, please tell me exactly what you are trying to do (provide the complete list of commands you are using), and exactly what happens instead of whatever you expected to happen (provide the full error message).

**Comment by mgeier** [comment]
Closing due to lack of response.
