### ISSUE TITLE
What is `blocksize` and callback's `frames` param?

### ISSUE THREAD

**Issue by hyansuper** [spatialaudio/python-sounddevice#238]
I need a little help to understand what is `blocksize` and callback's `frames` param.

At first I thought len(outdata) equals frames, and so it is with [play-a-sine-signal](https://python-sounddevice.readthedocs.io/en/0.3.15/examples.html#play-a-sine-signal) example (on my machine), but no with [play-a-very-long-sound-file](https://python-sounddevice.readthedocs.io/en/0.3.15/examples.html#play-a-very-long-sound-file)

I read the api section in doc:https://python-sounddevice.readthedocs.io/en/0.3.15/api/streams.html, but I still don't understand what is the relationship between blocksize, frames, and len(outdata). could you please explain more? Thank you

**Comment by mgeier** [comment]
Within the callback function, this is always `True`:

```python
frames == len(outdata)
```

The `frames` parameter is strictly speaking redundant. You don't ever have to use it, but sometimes the code looks nicer if you write `frames` instead of `len(outdata)`.

BTW, the documentation you are mentioning above contains this sentence:

> The third argument holds the number of frames to be processed by the stream callback. This is the same as the length of the input and output buffers.

The situation with `blocksize` is a bit more complicated, because there is a special case:
When you use `blocksize=0` (which is the default!), this means that the audio backend can choose whatever block size it wants. Especially, it is possible that the `frames` argument changes between invocations of the callback function!

However, if you set `blocksize` to a positive number, the callback will always be called with this exact number as `frames` argument.

Again, there is some information in the docs:

> The number of frames passed to the stream callback function [...]. The special value `blocksize=0` (which is the default) may be used to request that the stream callback will receive an optimal (and possibly varying) number of frames based on host requirements and the requested latency settings.

I hope this clears it up!
If you have further questions, don't hesitate to ask!

**Comment by hyansuper** [comment]
I insert `print(frames, len(outdata))` in the callback function in [play a very long sound file](https://python-sounddevice.readthedocs.io/en/0.3.15/examples.html#play-a-very-long-sound-file), turns out frames and len(outdata) are not the same!

**Comment by mgeier** [comment]
Oh, you might have found a bug then!

Can you please provide more details according to https://github.com/spatialaudio/python-sounddevice/blob/master/CONTRIBUTING.rst#reporting-problems?

**Comment by hyansuper** [comment]
I am using python3.8.0 on Ubuntu 18.04
````
hyan@laptop:~/aud$ python
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sounddevice as sd
>>> print(sd._libname)
libportaudio.so.2
>>> print(sd.get_portaudio_version())
(1246720, 'PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4')
>>> exit()
hyan@laptop:~/aud$ python -m sounddevice
   0 HDA Intel PCH: CX20590 Analog (hw:0,0), ALSA (2 in, 4 out)
   1 HDA NVidia: HDMI 0 (hw:1,3), ALSA (0 in, 8 out)
   2 HDA NVidia: HDMI 1 (hw:1,7), ALSA (0 in, 8 out)
   3 HDA NVidia: HDMI 2 (hw:1,8), ALSA (0 in, 8 out)
   4 sysdefault, ALSA (128 in, 128 out)
   5 front, ALSA (0 in, 4 out)
   6 surround40, ALSA (0 in, 4 out)
   7 surround51, ALSA (0 in, 4 out)
   8 surround71, ALSA (0 in, 4 out)
   9 pulse, ALSA (32 in, 32 out)
  10 dmix, ALSA (0 in, 2 out)
* 11 default, ALSA (32 in, 32 out)
```

**Comment by mgeier** [comment]
OK, thanks, now I would like to know how you invoked your modified `play_long_file.py` and what was shown on the terminal when running it.

**Comment by hyansuper** [comment]
modified play_long_file.py example:
```
def callback(outdata, frames, time, status):
    print(frames, len(outdata))
    assert frames == args.blocksize
    ....
```
outputs:
```
hyan@laptop:~/aud$ python play_long_file.py alert.wav 
2048 8192
2048 8192
2048 8192
2048 8192
2048 8192
....
```

**Comment by mgeier** [comment]
I was surprised for a moment, but then I saw the reason for the confusion:

The `play_long_file.py` example uses a `RawOutputStream`.
This means that the `outdata` argument in the callback function is *not* a NumPy array but a Python buffer object. When you use `len()` on such an object, you get the size of the data *in bytes*.

In this case, you should look at `stream.samplesize`, which is the number of bytes per sample.
Since the example uses `dtype='float32'`, you'll see that the sample size is 4.
You'll also have to check the number of channels (which in your file `alert.wav` seems to be 1).

The length in bytes of the output buffer is the number of frames times the number of channels times the sample size. This is why in your case `len(outdata)` is 4 times the number of `frames`, because the sample size is 4 and the number of channels is 1.

So I was wrong to say that above:

> Within the callback function, this is always `True`:
> 
> ```python
> frames == len(outdata)
> ```

This is only true when you use NumPy, i.e. when you use `Stream` and `OutputStream`.

When you use `RawOutputStream`, this is more accurate:

```python
frames * stream.samplesize * stream.channels  == len(outdata)
```

When you use `RawStream`, there are pairs of values for `samplesize` and `channels`, the second one is the value corresponding to the output:

```python
frames * stream.samplesize[1] * stream.channels[1]  == len(outdata)
```

Does that make sense?

**Comment by hyansuper** [comment]
Thank you, that answers my question
