### ISSUE TITLE
Refactor examples

### ISSUE THREAD

**Issue by vrslev** [spatialaudio/python-sounddevice#399]
Currently examples are clunky. I would like to refactor them, any thoughts, suggestions, argument against?

**Comment by mgeier** [comment]
Do you mean the argument parsing or is something else clunky?

I think the argument parsing is very useful, but it needs a lot of code.

I don't like to factor it out into a separate module, though, because I think the examples should be self-contained.

What are your thoughts and suggestions?

**Comment by vrslev** [comment]
I don’t mind argument parsing. My concerns are that it is hard to understand what’s going on in the examples. My suggestion is to simply refactor code to make it more readable and unify structure of standalone examples to make structure transparent.

**Comment by vrslev** [comment]
@mgeier As an example, here's how I would refactor `play_file.py`:

```python
import argparse
import sys
import threading
from contextlib import suppress

import sounddevice
import soundfile


def get_callback(data):
    current_frame = 0

    def callback(outdata, frames, time, status):
        nonlocal current_frame

        if status:
            print(status)

        chunk_size = min(len(data) - current_frame, frames)
        outdata[:chunk_size] = data[current_frame : current_frame + chunk_size]

        if chunk_size < frames:
            outdata[chunk_size:] = 0
            raise sounddevice.CallbackStop

        current_frame += chunk_size

    return callback


def play_long_file(data, samplerate, device):
    event = threading.Event()
    callback = get_callback(data)
    stream = sounddevice.OutputStream(
        samplerate=samplerate,
        device=device,
        channels=data.shape[1],
        callback=callback,
        finished_callback=event.set,
    )
    with stream:
        event.wait()  # Wait until playback is finished


def parse_args(argv):
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument(
        "-l",
        "--list-devices",
        action="store_true",
        help="show list of audio devices and exit",
    )
    args, remaining_args = parser.parse_known_args(argv)

    if args.list_devices:
        print(sounddevice.query_devices())
        parser.exit(0)

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        parents=[parser],
    )
    parser.add_argument(
        "filename", metavar="FILENAME", help="audio file to be played back"
    )

    def int_or_str(text):
        """Helper function for argument parsing."""
        try:
            return int(text)
        except ValueError:
            return text

    parser.add_argument(
        "-d",
        "--device",
        type=int_or_str,
        help="output device (numeric ID or substring)",
    )

    return parser.parse_args(remaining_args)


def main(argv):
    args = parse_args(argv)
    data, samplerate = soundfile.read(file=args.filename, always_2d=True)

    with suppress(KeyboardInterrupt):
        play_long_file(data=data, samplerate=samplerate, device=args.device)

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))

```

**Comment by mgeier** [comment]
I think that is actually clunkier than before.
Now I have to jump around when reading the code.
I have the feeling that having the argument parsing in the middle makes things worse, because I always have to jump over it when figuring out how stuff works.

Regarding `nonlocal` vs `global`: I would in general prefer `nonlocal` but in this case it's just not worth moving into a function for that. Also, the usage of `get_callback()` seems a bit clunky to me. Limiting the scope of `current_frame` is a good idea, but in this case it's not worth it IMHO.

The `suppress(KeyboardInterrupt)` makes the code a bit simpler, but I think it's better to catch all exceptions to avoid displaying a traceback, which might intimidate new users (for example when an invalid file name is chosen).

I don't like using `if __name__ == "__main__"` just for the sake of it, this seems like cargo cult programming. There are cases where it makes sense (e.g. https://github.com/spatialaudio/python-sounddevice/blob/master/examples/asyncio_coroutines.py and https://github.com/spatialaudio/python-sounddevice/blob/master/examples/asyncio_generators.py), but here we have a simple script that isn't supposed to be used as a Python module.

The `SystemExit` thing seems a bit out of place, since `main()` only ever returns 0. Also, I normally prefer `sys.exit()`, but TBH I have forgotten the reason why.

Passing `sys.argv[1:]` to `main()` is an antipattern (that is unfortunately used a lot). You should just call `main()` with empty arguments, and define the function with a default argument `argv=None`, which you simply can pass on. There is no need to mention `sys.argv` at all (in this case; if you need it you can check `if argv is None` and then get `sys.argv[1:]` inside the function). But just to make it clear: in this case I wouldn't use a `main()` function at all.

The length of the code isn't the most important thing, but it's still worth mentioning that your refactored version is longer than the original version, even though it doesn't contain the help text.

**Comment by vrslev** [comment]
The idea behind this issue is to make understanding example code easier. At first, when I encountered async examples I got confused. That’s why I proposed changes. I don’t mind getting rid of production noise (😃) like suppress or SystemExit to avoid confusion among beginners, but code is much clearer when we split it to functions.

**Comment by mgeier** [comment]
> make understanding example code easier

I'm very much for that.
But there might be individual differences in what people find "easy".

> code is much clearer when we split it to functions.

I don't agree.
I think it's harder to read, because now I have to jump around all the time instead of seeing a (more or less) linear sequence of statements.

> At first, when I encountered async examples I got confused.

I don't understand why you got confused by the async example, where the code is actually in functions, as you seem to prefer.

But in that case there is a good reason to put it into functions: they simply have to be functions, otherwise we couldn't use `async`.
And another reason: some of those functions are actually useful when the example is imported as a module. That's not the case in `play_file.py`.

> I don’t mind getting rid of production noise (smiley) like suppress or SystemExit to avoid confusion among beginners

My comments above are not at all limited to beginners (except where explicitly noted), you should also (and especially!) consider them for production code.

**Comment by vrslev** [comment]
@mgeier As I can see, changes I suggest is matter of preference. Since you don’t agree with my points, and that’s okay :) I will close the issue.
