### ISSUE TITLE
How to know which is the sound input device and which is the output device?

### ISSUE THREAD

**Issue by clouddea** [spatialaudio/python-sounddevice#416]
as title。

When I call `sd.query_devices()`, I get an array like:
![image](https://user-images.githubusercontent.com/31328538/175316601-a8bff091-76b1-49f9-9946-f55080cbc667.png)

However, which attribute of them can be used as a feature of device type?

**Comment by HaHeho** [comment]
What do you mean by device type?

**Comment by peder82** [comment]
It says in the last parenthesis (X in, Z out), it uses 0 for not applicable. 'In' is microphone and 'out' is speaker. So you have two devices which is microphones and one which is speaker.

**Comment by clouddea** [comment]
devices:
![WX20220707-161855](https://user-images.githubusercontent.com/31328538/177908958-b82d4497-29e3-4f55-a31c-8f47ef5bca70.png)

error:
![WX20220707-162019](https://user-images.githubusercontent.com/31328538/177908938-ef707438-56fd-4cd4-9998-f6d0c9502c41.png)

**Comment by HaHeho** [comment]
Each device has a separate entry for the three different backends that you have available on Windows. I don't know which one of these is to be preferred. I know ASIO (a fourth one) would be preferred for low-latency audio on Windows, but this requires specific drivers to be available for your device (which you don't seem to have).

I suppose just try which one is going to work for you. I believe you have to invoke the device name including the backend name (if there is multiple available), so that the device can be uniquely identified.
