### ISSUE TITLE
Concurrent recording and playback

### ISSUE THREAD

**Issue by arekbulski** [spatialaudio/python-sounddevice#76]
How can I continously keep recording and playing same samples? I have no problem running just a recording loop and stuffing samples in a list, or just playing a list of samples in a sequence. The problem is I need to keep recording and playing them concurrently. Essentially a loopback. Nothing I tried works, here is one code:
```py3
import sounddevice, timeit, time, threading, queue
audioqueue = queue.Queue()

def callback2():
    while 1:
        sample = sounddevice.rec(44100*2, samplerate=44100, channels=1, dtype='int16', blocking=1)
        audioqueue.put(sample.copy())
        print('added')

def callback3():
    while 1:
        sample = audioqueue.get()
        print('removed')
        sounddevice.play(sample, samplerate=44100, blocking=1)
        
thread2 = threading.Thread(target=callback2)
thread2.start()
thread3 = threading.Thread(target=callback3)
thread3.start()
while 1: pass
```
Please help, I am seriously stuck on this framework.

**Comment by mgeier** [comment]
`play()` and `rec()` are supposed to be very simple (and therefore quite limited) convenience functions. They cannot be used concurrently, because each of them calls `stop()` before doing their thing. They are definitely not thread-safe! Actually, nothing here is really thread-safe.

If you want to play a fixed-size sound and record at the same time, use `playrec()`.

If you want do do anything else, you have to use one of the lower-level "stream" objects and write your own callback function.

If you want a loopback, have a look at the docs: http://python-sounddevice.readthedocs.io/en/latest/#callback-streams.
There's even a separate example file [examples/wire.py](../blob/master/examples/wire.py).

There are more examples in the [examples/](../blob/master/examples) directory.

A word of advice: Don't create a thread until you know you really need one.
Since the callback function is already running in its own thread, you very often don't need to create any further threads.

**Comment by arekbulski** [comment]
Ah the docs explain how to use playrec, sorry it took me some time to understand how it works.

Problem is, this kinda works but each sample gets more and more noisy and after few seconds turns into just some wild noise:
```py3
sample = sounddevice.rec(44100*2, samplerate=44100, channels=1, dtype='int16', blocking=1)
while 1:
    sample = sounddevice.playrec(sample, samplerate=44100, channels=1, dtype='int16', blocking=1)
    print(len(sample))
```

**Comment by arekbulski** [comment]
Microphone gain is not that high, on speakers not boxes.

**Comment by mgeier** [comment]
If either the microphone gain or the loudspeaker level is too high, the level of the recordings will increase with each repetition until it sooner or later clips, which will create more or less ugly distortions.
Is this what's happening?

With any kind of feedback loop you have to be very careful with the feedback gain ...

What are you trying to do?

Something like Alvin Lucier's "I Am Sitting In A Room" (https://www.youtube.com/watch?v=fAxHlLK3Oyk)?

**Comment by arekbulski** [comment]
Oh what you just described, the clipping, seems to be what I experience. I will try to eliminate loopback.
