### ISSUE TITLE
Looping playback stops during call to PIL.Image.putdata()

### ISSUE THREAD

**Issue by GregoryTravis** [spatialaudio/python-sounddevice#77]
I am initiating a looping playback, and then generating an Image using PIL.  The sound loop stops when I call putdata().  The sound continues to not play after the call to putdata() returns -- during calls to resampy.resample().  Both of these, I believe, use native code.  Is there locking in the code that might cause this?

**Comment by mgeier** [comment]
This is strange ... and it somehow reminds me of #38 ...

Does the looping stop or does the playback stop?
IOW, does it also happen when you use the default `loop=False`?

Can you provide a minimal code example for me to reproduce the problem?

**Comment by GregoryTravis** [comment]
The looping and playback stop -- it stops in the middle of the loop.  Here's a short example:

[example.zip](https://github.com/spatialaudio/python-sounddevice/files/859079/example.zip)

**Comment by GregoryTravis** [comment]
To run that you'll have to supply input.wav, which should be at least a few seconds long.

**Comment by tgarc** [comment]
Heres the (modified code) I used:

```
import sys
import numpy
import sounddevice
import time
import wave
from PIL import Image

SAMPLING_RATE = 44100

wav = wave.open(sys.argv[1])
frames = wav.readframes(wav.getnframes())
shorts = numpy.fromstring(frames, numpy.int16)
shorts = shorts.reshape([-1, 2]) # correct for playback
seg = shorts[:,0]

subseg = seg[8*SAMPLING_RATE:10*SAMPLING_RATE]
print 'sound starts here'
sounddevice.play(subseg, SAMPLING_RATE, blocking=False, loop=True)

print repr(sounddevice.get_status())
time.sleep(1)
print repr(sounddevice.get_status())

width, height = 4256, 1256
arr = [0] * width
image = Image.new("RGB", (width, height))
print 'sound continues here despite program being busy'
data = [((255 if y > arr[x] and y < height/2 else 0) if arr[x] < height/2 else (255 if y < arr[x] and y > height/2 else 0), 0, 0) for y in xrange(0, height) for x in xrange(0, width)]


print repr(sounddevice.get_status())

print 'sound stops here'
# Loop just to make the silence last longer
for _ in xrange(5):
  image.putdata(data)
  print sounddevice.get_status()
print 'sound starts again around here'

time.sleep(1000)
```

And this is the output it gives me (with a 5 second file I had):

```
(venv2)tdos@thinkpad:~/dev/python-sounddevice$ python example.py input.wav 
sound starts here
<sounddevice.CallbackFlags: no flags set>
<sounddevice.CallbackFlags: output underflow>
sound continues here despite program being busy
<sounddevice.CallbackFlags: output underflow>
sound stops here
output underflow
output underflow
output underflow
output underflow
output underflow
sound starts again around here
```

So I suspect it's trying to acquire the GIL but can't.

**Comment by GregoryTravis** [comment]
Numpy and Resampy both use native code -- is that more, or less, likely to hold the GIL?

**Comment by tgarc** [comment]
@GregoryTravis This isn't an issue with either of those libraries - I found that the problem is related to pillow. Specifically, when it calls out `putdata` on the underlying `_imaging` library object; if you step through the program with `pdb` you'll see the audio is blocked while this call is being made. You may want to search and/or contact the `pillow` guys to see if this is a known issue.

**Comment by GregoryTravis** [comment]
Ok, this makes sense.  I'll bring this up with Pillow but I have a feeling it's not something they plan to fix any time soon.  In the meantime I'll have to spawn a subprocess for my looping audio.

**Comment by mgeier** [comment]
I'm not sure if this really is a bug, probably they hold the GIL on purpose, in order to avoid somebody else changing the list that's passed to `putdata()`?

As an alternative to the subprocess work-around, you could also try to implement your own audio callback in C. This way the GIL doesn't affect the ongoing audio playback.
I've started such a thing in https://github.com/mgeier/python-rtmixer/, but it is still very much work in progress. It doesn't support looping, for example, but this is definitely something that could be implemented.

**Comment by GregoryTravis** [comment]
That's a really good idea.  I'll re-open this if I make any progress on that.
