### ISSUE TITLE
Proposal: Have sounddevice.play/stop/playrec reuse open streams when possible

### ISSUE THREAD

**Issue by tgarc** [spatialaudio/python-sounddevice#79]
I had a question related to #75 ...You had said:

| After stop(), there is now way (and IMHO shouldn't be) to "open" the stream again.

So you wouldn't be interested in modifying the behavior so that `sounddevice.stop()` actually calls `PaStopStream` and `sounddevice.start()` only opens a new stream if needed? I was thinking about implementing this behavior to avoid unnecessary loading and unloading of the device driver. I think it makes sense to re-use the open stream unless the user is asking for a stream with some new/different parameters.

**Comment by mgeier** [comment]
I'm skeptical, because I think this would very much increase the amount of code.

But if not, I'm OK with it.

My original idea for `play()`/`rec()`/`playrec()` was to be used in an interactive session and probably in some trivial scripts. The main goal was convenience, not being nice to the device driver. People who want to use the `sounddevice` module as part of a "serious" application, were supposed to create their own specialized callback function. But it looks like many people are either too lazy or too intimidated to do that.

An alternative would probably be to create some kind of "player" and/or "recorder" class to be used in applications, which internally takes care of a single stream. The callback would be basically a Python implementation of what I'm currently implementing in C for https://github.com/mgeier/python-rtmixer/. Once this is finshed, this is what people should actually be using in their "serious" applications.

**Comment by tgarc** [comment]
Yeap, I understand the concerns. The reason I brought it up is I suspect that this would causes issues if you're making play() calls in quick succession, at least on some platforms, but I guess this hasn't really come up yet so I suppose it's sort of a non-issue. (BTW I know there was a previous issue where a user was having issues doing exactly what I describe, but it seems like you've sorted that out).

> An alternative would probably be to create some kind of "player" and/or "recorder" class to be used in applications, which internally takes care of a single stream.

True. I would think that many users may not even need anything but the most basic functionality from the audio callback. I'm not sure whether this is worth broaching ATM though.

I'll close this out for now, as I can't really justify this change with any clear improvement or advantage.
