### ISSUE TITLE
Question: How to Implement a "PTT" based on events

### ISSUE THREAD

**Issue by x11tete11x** [spatialaudio/python-sounddevice#86]
Hi!, first, thx for your work!, i have some code that works with pyaudio that i wanna port to sound device works in this way:
PTT= Push to Talk

i have an Input Stream that:
1_ User press button "record" from a QT GUI, that trigger "streamInput.start_stream()"
2_ The stream Input start to record to an a var that then i send over a udp socket
3_ User release the button "record" from GUI, that trigger "streamInput.stop_stream()" that finish that record

it's possible to do something similar in sounddevice? (i dont find any way to start and "pause" a stream) BTW, for now i do this:

def start_record():
    global myrecording
    myrecording = sd.rec(60 * fs, samplerate=fs, channels=2, dtype='float64')

def stop_record():
    sd.stop()

works in a pretty same way (except for that limit to record, that shouldn't be much problematic, it's a PTT, it's made for make short comunications between interlocutors)

Thx!

**Comment by tgarc** [comment]
It sounds like you've implemented what you wanted with sounddevice. What's the issue? Is there some functionality you're missing?

**Comment by x11tete11x** [comment]
Yeah, works :P but perhaps you know another way or better way to implement that :D

**Comment by tgarc** [comment]
Well, without knowing your limitations I don't know how I can help ¯\\\_(ツ)_/¯

**Comment by mgeier** [comment]
@x11tete11x 

The `sd.rec()` function is meant to be really quick and simple to use, but it is not very flexible. You have to specify the duration of the recording beforehand, and if you call `sd.stop()`, you get an array which is only partially filled with meaningful data, the rest is garbage (and you don't know exactly where the meaningful data ends).

If you need more flexibility, you should implement your own callback function (similar to how you would do it with PyAudio).
Within your callback function you could wait for your trigger, and once it comes in, you can start sending/receiving data via UDP.
You should probably use a queue for transporting the audio data in order to avoid blocking the audio callback if the UDP communication needs some extra time. You can have a look at the example applications for how to use a queue.

Apart from that, as @tgarc said, if you need more help you should provide more details about what you want to achieve.

Just out of curiosity: If you already have working code for PyAudio, what's the reason to port it?

**Comment by x11tete11x** [comment]
@mgeier Thx for clarify!, then i will looking how to implement my callback function
The reason to switch from pyaudio to sounddevice is because pyaudio under certains circunstances give me "alsa underruns" that chop my audio, and other audio problems, look at this https://github.com/raspberrypi/linux/issues/994 then few people say that switching to sounddevice all problems gone, so i wanna try
