### ISSUE TITLE
the stop() function freezes the execution and the sound is disturbed

### ISSUE THREAD

**Issue by azi92rach** [spatialaudio/python-sounddevice#87]
Hi! I started to use the sounddevice for an implementation of a system that trig the sound when an event occurs and stops when for an other event.
I noted that the stop() function freezes the execution. This happen only on Ubuntu while on Macbook works fine. I didn't understand why. 
Moreover,  on Ubuntu when the sounddevice is running in an implementation the sound played is disturbed, i.e. not continuously.  If I use the wait() function works but I can't use it since I need to stop the sound by an event. 
On Mackbook everything works with the same code, so I think that the problem is related with Ubuntu. 
Can you help me?

**Comment by mgeier** [comment]
> the stop() function freezes the execution

Are you calling the `stop()` function from the same thread as `play()`?

> the sound played is disturbed, i.e. not continuously.

What else happens during playback?

Could you try to come up with a minimal code example that shows those problems?

Without seeing the code and without being able to reproduce it, it's hard to find the cause of those problems.

**Comment by UmSenhorQualquer** [comment]
Hi,

here is a simple code

```python

import sounddevice as sd
import numpy as np
​
fs = 44100
data = np.random.uniform(-1, 1, 44100*5)
sound = np.int16(data / np.max(np.abs(data)) * 32767)
sd.default.samplerate = fs
sd.play(sound, blocking=False)
sd.stop()
```

The stop() function freezes the application if the sound doesn't finish playing.

**Comment by mgeier** [comment]
@UmSenhorQualquer Thanks for the code example!

This exposed another error (invalid stream pointer) which was introduced in #75 which I hopefully fixed in 73b260cb4f3f1240de636e29ccf6e0ca90f03d8b.

The error described in this issue seems to only occur with older PortAudio versions.
This should be fixed with #88.

@azi92rach, @UmSenhorQualquer: Can you please check if that works for you?

@azi92rach: I don't know what you mean by "sound played is disturbed", can you please describe this problem in more detail and provide code to reproduce it?

**Comment by azi92rach** [comment]
@mgeier thanks to fix the stop() issue. I tested it and it works. @UmSenhorQualquer also for you? 
Actually I cannot provide you some example about the "sound disturbed" problem because I running it using hardware that you haven't.
I let you know if I find some example to show you. Anyway now the problem occurs less times than before, maybe fixing the stop() problem you fix also this one. Only some times the sound it is discontinuous.  In attach an example, but I am using an other hardware and other libraries instead of the keyboard. 

CODE EXAMPLE: 

import sounddevice as sd
import numpy as np
import cv2

fs = 44100
data = np.random.uniform(-1, 1, 44100*5)
sound = np.int16(data / np.max(np.abs(data)) * 32767)
sd.default.samplerate = fs

while(1):
    im = np.random.rand(800,800,3)
    cv2.imshow('im',im)
    a = cv2.waitKey(1) & 0xff
    if a == ord('q'): break
    elif a == ord('z'): 
        sd.play(sound, blocking=False)
    elif a == ord('x'):
        sd.stop()

**Comment by tgarc** [comment]
@azi92rach So you're using OpenCV through the python bindings? This could be the source of your problem. Are you experiencing pauses (momentary silence) in the audio playback? Or is the audio being 'disturbed' in some other way?

**Comment by mgeier** [comment]
@azi92rach Thanks for testing!

As you suspected, your example works fine on my computer.

I'm leaving this issue open for now until we know more about the "disturbed" problem.

**Comment by azi92rach** [comment]
@tgarc it was just an example! Actually on my script I am not using openCV. 
@mgeier thanks for your time. I hope to resolve it because it is very important for our project. 

I will try to explain you my code.
I am using the pybpod-api ibrary (http://pybpod-api.readthedocs.io/en/latest/) to control the Bpod (a hardware used for behavioural experiments).
Actually, when the Bpod catch an event, it send to the computer a byte (a code, e.g. 55). In this case the sound starts to play. Then for an other event (e.g. 66) it stops. 
This is the code: 
[IRtest_sounddevice.txt](https://github.com/spatialaudio/python-sounddevice/files/1122951/IRtest_sounddevice.txt)

I am not sure that this could be useful because you need the hardware to use it. 

 The problem is that it works perfectly on Macbook, but on Ubuntu there are these very small pauses (momentary silence) in the audio playback. It looks like that the computer is busy some times.

**Comment by tgarc** [comment]
> @tgarc it was just an example! Actually on my script I am not using openCV.

It still may be the same issue, especially since you say you have pauses in the audio. I'm wondering if you're not experiencing the same issue as the one reported in #77: namely that some method in your program is holding onto the Python Global Interpreter Lock without letting anyone else interrupt until it is complete (therefore blocking the audio callback). 

If you're using python bindings that call into a compiled extension (like a C library), this is likely to be the cause of your issue.

**Comment by azi92rach** [comment]
Thank you @tgarc! I will check it. 
One thing more is that using the library "pygame" (https://github.com/pygame/pygame) it works fine. 
The unique problem is that is slow for my application. The time between an event and the triggering has to be less than 15ms. @mgeier  I saw that sounddevice can play the sound before 15ms. 

Moreover, why does this happen only on Ubuntu while on Macbook works fine? I didn't understand it.

**Comment by tgarc** [comment]
> why does this happen only on Ubuntu while on Macbook works fine?

If the problem is what I was speculating that could be due to a large variety of reasons. Bad concurrent/multi-threaded code will show different effects on different platforms. It's likely that in a slightly different program mac os would experience the same issue you describe.

I can't really speak to why your program works on pygame since I don't know exactly how the audio streaming works there, but it's perfectly possible and even likely that pygame handles all the audio streaming outside of python. With sounddevice, the audio data is fed directly from python so the audio backend needs access to python at regular intervals.

**Comment by mgeier** [comment]
I would also assume that pygame's audio callback is running without ever directly invoking the Python interpreter. And I guess (but I don't really know) that in order to communicate with Python, it does some buffering on its own, which causes the additional delay.

@azi92rach

You might be able to fine-tune pygame's settings to reduce its buffer sizes?

To avoid the GIL problem, I started implementing https://github.com/mgeier/python-rtmixer/.
This is still quite experimental, but you might try if it works for your use case?

**Comment by azi92rach** [comment]
I found the problem on the other library. Thanks!

**Comment by tgarc** [comment]
@azi92rach could you give a brief explanation of how you were able to fix your problem? Just in case someone else runs into the same/similar issue

**Comment by azi92rach** [comment]
yes of course! The other library had a loop and it has a function that sleep(0.2) to free the CPU a bit. 
So, now I am playing the sounddevice in an other process and it works.
