### ISSUE TITLE
Converting a .wav into numpy array

### ISSUE THREAD

**Issue by jeffdbeats** [spatialaudio/python-sounddevice#93]
How would one simply convert a .wav into a NumPy Array? I have been searching all over and it seems like you need SciPy? I can not find a really good simple example.

Instead of doing sd.play(numpyarray) I wonder if it would be possible to just simply implement a way to do sd.play("file.wav")?

Ultimately my goal is to use sounddevice for its sd.playrec feature, that is exactly what I need.

Thanks!
Jeff

**Comment by mgeier** [comment]
There is a thing called [Separation of Concerns](https://en.wikipedia.org/wiki/Separation_of_concerns), which is why the `sounddevice` module cannot (and will never) handle reading and writing of sound files. There are several other libraries you can use for that.

I've written an overview about such libraries here: http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/audio-files/index.ipynb.

I recommend the `soundfile` module, but if you prefer, you can also use SciPy or whatever.

And that's part of the reason why this is not included in the `sounddevice` module. Different people prefer different libraries, and some people don't need to handle audio files at all.

> I can not find a really good simple example.

What about the [examples](../blob/master/examples/)?

> Instead of doing `sd.play(numpyarray)` I wonder if it would be possible to just simply implement a way to do `sd.play("file.wav")`?

Sure, you can do something like that in your own code.

**Comment by jeffdbeats** [comment]
Thanks @mgeier ! I will read separation of concerns, I have never heard of that before.

I saw that example but at first I didn't understand it, I asked a [stackoverflow question](https://stackoverflow.com/questions/45124928/numpy-array-holding-wav-audio-data-for-sounddevice) and it helped clear it up for me. 

```
filename = "file.wav"
data, fs = sf.read(filename, dtype='float32')
sd.play(data, fs)
```

I ended up using the soundfile module and it worked great. The audio from sounddevice sounds crystal clear on my system!

Thanks for creating sounddevice!
