### ISSUE TITLE
playrec() recording is sped up

### ISSUE THREAD

**Issue by jeffdbeats** [spatialaudio/python-sounddevice#94]
I have got the `playrec()` feature to almost work, for some reason the recording is slightly sped up. I can not think of why the after.wav file would be playing slightly faster. Here is what I have so far:

            
            filetoplay = "before.wav"
            filetorecord = "after.wav"
            data, fs = sf.read(filetoplay, dtype='float32')
            myrecording = sd.playrec(data, fs, 2)
            sd.wait()
            sf.write(filetorecord, myrecording, 48000)

Thanks!
Jeff

**Comment by jeffdbeats** [comment]
The file is playing faster because the sample rate of before.wav was 44.1khz and the after is 48khz, I am using ffmpeg to preprocess my files so changing before.wav from 44100 to 48000 solves the problem.

**Comment by tgarc** [comment]
@jeffdbeats 

Take a look at the example for [playrec](http://python-sounddevice.readthedocs.io/en/0.3.8/#simultaneous-playback-and-recording). You'll see there that playrec returns the recording as a numpy array. So you'd have to change

    sd.playrec(data, fs, 2)
to
        
    data2 = sd.playrec(data, fs, 2)

> I can not think of why the after.wav file would be playing slightly faster.

So you're above code actually just saves a copy of your input *but* you explicitly specify a samplerate of 48000. I'm willing to be that the samplerate of your input is actually lower than 48000, which makes it sound slower when played back

But it sounds like you're missing some fundamental concepts to python/programming in general. When you write:

    sd.playrec(data, fs, 2, out=data2)

Python gives you a NameError. Why? Because ``data2`` hasn't been declared yet! At this point in the program Python has no idea what the heck data2 is. 

Anyway, I don't want to bore you with further details because I have no idea what level of programming you're at and what you're willing to learn. But if you do want to learn and don't have people or schooling to learn from...I recommend something like [codeacademy](https://www.codecademy.com/learn/python) or something on [Coursera](https://www.coursera.org/learn/python).

**Comment by jeffdbeats** [comment]
Thanks @tgarc you are exactly right with both issues, I realised that my samplerates where different and found an [example on this page ](https://pypi.python.org/pypi/sounddevice)with myrecording = sd.playrec(). Thanks for posting! I just started learning python a couple of days ago, coming from jquery and php so far I am loving what it is capable of! I will have to check out codeacademy! I think python will become one of my most used languages.
